name: iOS Tests

on:
  workflow_call:
    inputs:
      scheme:
        description: 'Xcode scheme name to test'
        required: true
        type: string
      xcresult-name:
        description: 'Name of the xcresult bundle (e.g., "MyApp.xcresult")'
        required: true
        type: string
    secrets:
      CODECOV_UPLOAD_TOKEN:
        description: 'Codecov upload token'
        required: false

jobs:
  automated-tests:
    runs-on: macos-15
    permissions:
      checks: write # Need write permission to add test result check.
    env:
      CODECOV_UPLOAD_TOKEN: ${{ secrets.CODECOV_UPLOAD_TOKEN }}
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup iOS
      uses: customerio/mobile-ci-tools/github-actions/ios/setup-ios/v1@main
    
    # If running tests fails, sometimes it's because of scheme name is wrong. This gives us all available schemes.
    - name: Get XCode schemes 
      run: xcrun xcodebuild -list

    - name: Setup Ruby to run Fastlane 
      uses: ruby/setup-ruby@354a1ad156761f5ee2b7b13fa8e09943a5e8d252 # v1.229.0
      with:
        ruby-version: '3.2'
        bundler-cache: true # install dependencies in Gemfile, including Fastlane.

    - name: Run tests 
      uses: maierj/fastlane-action@5a3b971aaa26776459bb26894d6c1a1a84a311a7 # v3.1.0
      with:
        lane: 'scan'

    # https://about.codecov.io/blog/pre-converting-xcresult-files-for-codecov-using-xcresultparser/
    - name: Generate code coverage report from .xcresult/ that can be converted to codecov format
      run: |
        brew tap a7ex/homebrew-formulae && brew install xcresultparser
        xcresultparser --output-format cobertura "${{ inputs.xcresult-name }}" > ".build/coverage.xml"
      if: env.CODECOV_UPLOAD_TOKEN != ''
  
    - name: Upload code coverage report 
      uses: codecov/codecov-action@0f8570b1a125f4937846a11fcfa3bcd548bd8c97 # v4.6.0
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_UPLOAD_TOKEN }} 
      with: 
        files: .build/coverage.xml
        fail_ci_if_error: true # fail if upload fails so we can catch it and fix it right away.
        verbose: true
      if: env.CODECOV_UPLOAD_TOKEN != '' 

    - name: Upload test report 
      uses: actions/upload-artifact@v4
      with:
        name: xcode-test-report
        path: test-report.*
      if: ${{ always() }}
      
    - name: Publish test results
      uses: mikepenz/action-junit-report@db71d41eb79864e25ab0337e395c352e84523afe  # v4.3.1
      with:
        check_name: XCode macOS tests - Results
        report_paths: test-report.xml
        github_token: ${{ secrets.GITHUB_TOKEN }}
        fail_on_failure: true
        require_tests: true
      if: ${{ always() }} # if running tests fails, we still want to parse the test results

