name: iOS Lint

on:
  workflow_call:

jobs:
  format-and-lint:
    name: Assert that code has been linted and formatted
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      
      - name: Install binny to run lint tools 
        run: |
          curl -L --output binny https://github.com/customerio/binny/releases/download/latest/binny-macos-x86_64
          chmod +x binny 
        shell: bash
        
      - name: Run swiftformat. Fail if any errors. 
        run: make format && git diff --exit-code
        shell: bash
        
      - name: Run swiftlint. Fail if any errors. 
        run: make lint
        shell: bash
